export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_ERR = "AUTH_USER_ERR";
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";


export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";

export const GET_SINGLE_PROJECT = "GET_SINGLE_PROJECT";
export const GET_SINGLE_PROJECT_ERROR = "GET_SINGLE_PROJECT_ERROR";
export const PROJECT_TITLE_EDITABLE = "PROJECT_TITLE_EDITABLE";

export const UPDATE_PROJECT_TITLE = "UPDATE_PROJECT_TITLE";
export const UPDATE_PROJECT_TITLE_ERROR = "UPDATE_PROJECT_TITLE_ERROR";



