export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_ERR = "AUTH_USER_ERR";
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";


export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";

export const GET_SINGLE_PROJECT = "GET_SINGLE_PROJECT";
export const GET_SINGLE_PROJECT_ERROR = "GET_SINGLE_PROJECT_ERROR";
export const PROJECT_TITLE_EDITABLE = "PROJECT_TITLE_EDITABLE";

export const UPDATE_PROJECT_TITLE = "UPDATE_PROJECT_TITLE";
export const UPDATE_PROJECT_TITLE_ERROR = "UPDATE_PROJECT_TITLE_ERROR";


export const CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT";
export const CREATE_NEW_PROJECT_ERROR = "CREATE_NEW_PROJECT_ERROR";



export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";


export const ADD_IDEA_TO_PROJECT = "ADD_IDEA_TO_PROJECT";
export const ADD_IDEA_TO_PROJECT_ERROR = "ADD_IDEA_TO_PROJECT_ERROR";


export const DELETE_IDEA_FROM_PROJECT = "DELETE_IDEA_FROM_PROJECT";
export const DELETE_IDEA_FROM_PROJECT_ERROR = "DELETE_IDEA_FROM_PROJECT_ERROR";


export const UPDATE_IDEA_PRIORITY = "UPDATE_IDEA_PRIORITY";
export const UPDATE_IDEA_PRIORITY_ERROR = "UPDATE_IDEA_PRIORITY_ERROR";



//idea Filters

export const IDEAS_OLD_TO_NEW = "IDEAS_OLD_TO_NEW";
export const IDEAS_NEW_TO_OLD = "IDEAS_NEW_TO_OLD";

export const IDEAS_A_TO_Z = "IDEAS_A_TO_Z";
export const IDEAS_Z_TO_A = "IDEAS_Z_TO_A";

export const IDEAS_PRIORITY_TOP_TO_BOTTOM = "IDEAS_PRIORITY_TOP_TO_BOTTOM";
export const IDEAS_PRIORITY_BOTTOM_TO_TOP = "IDEAS_PRIORITY_BOTTOM_TO_TOP";



